baseurl:
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8
markdown: kramdown
kramdown:
    input: GFM
name: elainte
description: 明天,你好。
domain: elainte.github.io
avatar: http://elainte.github.io/avatar.png